notifications:
  email: false
language: C
sudo: required
branches:
  only:
    - master
script:
  - cd test && make build_and_run
  - cd examples/doxygen && make example
  - $TRAVIS_BUILD_DIR/.travis-deploy.sh
